"""Relation nodes: Bridge, Convergence, BlindSpot.

These are first-class nodes (queryable, diffable) rather than ad-hoc edges because
coalition logic is the point of the tool, not an implementation detail.
"""

from __future__ import annotations

from pydantic import Field

from afls.schema.base import BaseNode, NodeRef


class Bridge(BaseNode):
    """A normative translation between two camps' framings.

    Lets camp A's position be reframed in camp B's language *without* collapsing
    the normative difference. Caveats mark the parts that don't translate.
    """

    kind: str = Field(default="bridge", frozen=True)
    from_camp: NodeRef
    to_camp: NodeRef
    translation: str = Field(min_length=1)
    caveats: list[str] = Field(default_factory=list)


class Convergence(BaseNode):
    """Coalition logic as data: camps X, Y, Z agree on intervention W for different reasons."""

    kind: str = Field(default="convergence", frozen=True)
    intervention_id: NodeRef
    camps: list[NodeRef] = Field(min_length=2)
    divergent_reasons: dict[NodeRef, NodeRef] = Field(
        default_factory=dict,
        description="camp_id -> normative_claim_id: why this camp arrives at this intervention.",
    )


class BlindSpot(BaseNode):
    """Tool-generated flag: a camp or position the operator is under-weighting.

    Generated by cross-referencing operator priors against the camp graph.
    """

    kind: str = Field(default="blindspot", frozen=True)
    against_prior_set: str = Field(description="Which operator prior set this flags against.")
    flagged_camp_id: NodeRef
    reasoning: str = Field(min_length=1)
